nhk_umai:
    enable: true
    program_name: "NHK うまいッ！"
    entry_urls:
        - "http://www6.nhk.or.jp/umai/recipe/index01.html"
        - "http://www6.nhk.or.jp/umai/recipe/index02.html"
        - "http://www6.nhk.or.jp/umai/recipe/index03.html"
        - "http://www6.nhk.or.jp/umai/recipe/index04.html"
    cache_dir: ~
    processed_list_filename: ~
    tag_names: ~
danshigohan:
    enable: true
    program_name: "テレ東 男子ごはん"
    entry_urls:
        - "https://www.tv-tokyo.co.jp/danshigohan/recipe/"
rsk_cooking_recipe:
    enable: true
    program_name: "RSK クッキング・レシピ"
    entry_urls:
        - "http://www.rsk.co.jp/tv/recipe/"
oshaberi:
    enable: true
    program_name: "ABC 上沼恵美子のおしゃべりクッキング"
    entry_urls:
        - "https://www.asahi.co.jp/oshaberi/main.html"
three_minutes_cooking:
    enable: true
    program_name: "NTV キューピー3分クッキング"
    entry_urls:
        - "http://www.ntv.co.jp/3min/airdate/"
oishimeshi:
    enable: true
    program_name: "CSネット コープのおいしめし"
    entry_urls:
        - "https://www.csnet.coop/movies/recipemovie.cgi?template=index.html"